const mongoose = require("mongoose");

// Define the user schema
const userSchema = new mongoose.Schema({
  // id: { type: Number, required: false }, // autogenerated by Mongodb with attribute _id
  uuid: { type: String, required: true },
  firstName: { type: String, required: false },
  lastName: { type: String, required: false },
  email: { type: String, required: false },
  phoneNumber: { type: String, required: false },
  username: { type: String, required: true },
  password: { type: String, required: true },
  balance: { type: Number, required: false, default: 0 },
  transactions: [{ type: mongoose.Schema.Types.ObjectId, ref: "Transactions", required: false }],
  bankAccounts: [{ type: mongoose.Schema.Types.ObjectId, ref: "BankAccount", required: false }],
  createdAt: { type: Date, default: Date.now },
  modifiedAt: { type: Date, default: Date.now }
});

// Create the User model
const User = mongoose.model("User", userSchema);

module.exports = User;